POST http://localhost:4157/deposit HTTP/1.1
content-type: application/json

{
  "accountId": "c0c235c6-3343-4696-9033-6f4e3bf9e8c7",
  "assetId": "BTC",
  "quantity": 1000000
}

###

POST http://localhost:4157/withdraw HTTP/1.1
content-type: application/json

{
  "accountId": "c0c235c6-3343-4696-9033-6f4e3bf9e8c7",
  "assetId": "BTC",
  "quantity": 115000
}

###

POST http://localhost:4157/place-order HTTP/1.1
content-type: application/json

{
  "accountId": "c0c235c6-3343-4696-9033-6f4e3bf9e8c7",
  "marketId": "BTC-USD",
  "side": "sell",
  "quantity": 24,
  "price": 10
}
